# Generated by Django 5.1.2 on 2024-11-11 13:53

import boards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_alter_boardbutton_button_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardbutton',
            name='button_audio',
            field=models.FileField(null=True, upload_to=boards.models.user_directory_path),
        ),
    ]
